---
name: Build and upload package to PPA

on: workflow_dispatch

jobs:
  ppa-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install devscripts
        run: sudo apt install devscripts dh-make dh-golang -y

      - name: Import GPG Key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" --import

      - name: Build debian package
        run: sudo debuild -uc -us -S -sa
          -k"shubhamtatvamasi@gmail.com"
          -p"gpg --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" --pinentry-mode loopback"

      - name: Sign changes
        run: debsign ../*.changes
          -k"shubhamtatvamasi@gmail.com"
          -p"gpg --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" --pinentry-mode loopback"

      - name: Upload package
        run: dput --unchecked ppa:shubhamtatvamasi/helloworld ../*.changes
