---
name: Build and upload package to PPA

on: workflow_dispatch

jobs:
  ppa-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install devscripts
        run: sudo apt install devscripts dh-make dh-golang golang-any -y

      - name: Import GPG Key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" --import

      - name: Build and Upload packages
        run: |
          for distro in $(distro-info --supported); do

            sed "s/distro/${distro}/" -i debian/changelog

            sudo debuild -uc -us -S -sa \
              -k"shubhamtatvamasi@gmail.com" \
              -p"gpg --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" --pinentry-mode loopback"

            debsign ../*.changes \
              -k"shubhamtatvamasi@gmail.com" \
              -p"gpg --batch --passphrase "${{ secrets.GPG_PASSPHRASE }}" --pinentry-mode loopback"

            dput --unchecked ppa:shubhamtatvamasi/helloworld ../*.changes

            rm -rf ../*.{changes,build,buildinfo,dsc,upload,tar.gz}

            sed "s/${distro}/distro/" -i debian/changelog

          done
